openapi: 3.0.3
info:
  title: My_api
  version: 1.0.0
paths:
  /cities:
    post:
      description: Get all possible cities with their corresponding IDs
      operationId: city_Explorer
      responses:
        200:
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/City_name'
              example: "[\r\n{\r\n\"id_city\": \"1\",\r\n\"city\": \"Athens\"\r\n\ },\r\n{\r\n\"id_city\": \"2\",\r\n\"city\": \"Piraeus\"\r\n},\r\n\ {\r\n\"id_city\": \"3\",\r\n\"city\": \"Tokyo\"\r\n}\r\n]\r\n"
  /countries:
    post:
      description: Given a city and its corresponding ID return the country and its
        corresponding ID
      operationId: country_Explorer
      parameters:
      - name: id
        in: query
        required: false
        schema:
          type: string
        example: ?id=1
      x-codegen-request-body-name: class
      responses:
        200:
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Country_name'
              example: "{\r\n\"req_body\": {\r\n\"id_city\": \"1\",\r\n\"city\": \"\ Athens\"\r\n},\r\n\"id_country\": \"1\",\r\n\"country\": \"Greece\"\ \r\n}"
components:
  schemas:
    Country_name:
      required:
      - req_body
      type: object
      properties:
        id_country:
          type: string
        country:
          type: string
        req_body:
          $ref: '#/components/schemas/req_body_class'
    City_name:
      type: object
      properties:
        id_city:
           $ref: "#/components/schemas/Dependency_query_1"
        city:
          type: string
    req_body_class:
      type: object
      properties:
        id_city:
          type: string
        city:
          type: string
    Dependency_query_1:
      type: object
      properties:
        id:
          type: string
        country_Explorer:
          type: 
