openapi: 3.0.0
info:
  title: ENTsoe V3 Copy
  version: 1.0.0
servers:
  - url: https://api.diem-platform.com
paths:
  /api/v3/data/entsoeaggregatedinstalledgenerationcapacity/2017/2/26/1000:
    get:
      tags:
        - General
      summary: Aggregated Installed Generation Capacity
      operationId:  Aggregated Installed Generation Capacity
      description: 
      x-codegen-request-body-name: rest_service13request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              $ref: "#/components/schemas/rest_service13request"
            example: "{\r\n    \"areaRef\":\"BELGIUM_BE_CTA_CTA\",\r\n    \"timezone\":\"CET\",\r\n    \"prodType\":\"waste\"\r\n}"
              areaRef: BELGIUM_BE_CTA_CTA
              timezone: CET
              prodType: waste
      parameters:
        - name: x-auth-key
          in: header
          schema:
            type: string
          example: ASLDKJASDJK2534S
      responses:
        '200':
          description: Successful response
          content:
  /api/v3/data/entsoedaaggregatedgenforecastfortype/2021/10/28/20:
    get:
      tags:
        - General
      summary: Day Ahead Generation Forecast of particular RES
      operationId:  Day Ahead Generation Forecast of particular RES
      description: 
      x-codegen-request-body-name: rest_service38request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              $ref: "#/components/schemas/rest_service38request"
            example:
              areaRef: GREECE_GR_CTY_CTY
              prodType: solar
      parameters:
        - name: x-auth-key
          in: header
          schema:
            type: string
          example: ASLDKJASDJK2534S
      responses:
        '200':
          description: Successful response
          content:
  /api/v3/data/entsoedaaggregatedgenforecasttotalres/2021/10/28/20:
    get:
      tags:
        - General
      summary: Day Ahead Generation Forecast Total RES
      operationId:  Day Ahead Generation Forecast Total RES
      description: 
      x-codegen-request-body-name: rest_service62request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              $ref: "#/components/schemas/rest_service62request"
            example: "{\r\n    \"areaRef\":\"GREECE_GR_CTY_CTY\",\r\n    \"prodType\":\"solar\"\r\n}"
              areaRef: GREECE_GR_CTY_CTY
              prodType: solar
      parameters:
        - name: x-auth-key
          in: header
          schema:
            type: string
          example: ASLDKJASDJK2534S
      responses:
        '200':
          description: Successful response
          content:
  /api/v3/data/entsoedatotalloadforecast/2021/10/28/20:
    get:
      tags:
        - General
      summary: Day Ahead Total Load Forecast
      operationId:  Day Ahead Total Load Forecast
      description: 
      x-codegen-request-body-name: rest_service86request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              $ref: "#/components/schemas/rest_service86request"
            example: "{\r\n    \"areaRef\":\"GREECE_GR_CTY_CTY\"\r\n}"
              areaRef: GREECE_GR_CTY_CTY
      parameters:
        - name: x-auth-key
          in: header
          schema:
            type: string
          example: ASLDKJASDJK2534S
      responses:
        '200':
          description: Successful response
          content:
  /api/v3/data/entsoenetpositionsdaily/2020/10/28/20:
    get:
      tags:
        - General
      summary: Net Positions Daily
      operationId:  Net Positions Daily
      description: 
      x-codegen-request-body-name: rest_service109request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              $ref: "#/components/schemas/rest_service109request"
            example: "{\r\n    \"areaRef\":\"CROATIA_HR_BZN_BZN\"\r\n}"
              areaRef: CROATIA_HR_BZN_BZN
      parameters:
        - name: x-auth-key
          in: header
          schema:
            type: string
          example: ASLDKJASDJK2534S
      responses:
        '200':
          description: Successful response
          content:
  /api/v3/data/productiontypes:
    get:
      tags:
        - General
      summary: productiontypes Copy
      operationId:  productiontypes Copy
      description: 
      parameters:
        - name: x-auth-key
          in: header
          schema:
            type: string
          example: ASLDKJASDJK2534S
      responses:
        '200':
          description: OK
          headers:
            X-Powered-By:
              schema:
                type: string
              example:
                value: Express
            Access-Control-Allow-Origin:
              schema:
                type: string
              example:
                value: '*'
            Access-Control-Allow-Headers:
              schema:
                type: string
              example:
                value: Origin, X-Requested-With, Content-Type, Accept, x-auth-token
            Access-Control-Allow-Methods:
              schema:
                type: string
              example:
                value: POST, GET, PUT, DELETE, OPTIONS
            Content-Type:
              schema:
                type: string
              example:
                value: application/json; charset=utf-8
            Content-Length:
              schema:
                type: integer
              example:
                value: '3159'
            ETag:
              schema:
                type: string
              example:
                value: W/"c57-dWZt4DWhld6NkBTXP7SRaZTKD/E"
            Date:
              schema:
                type: string
              example:
                value: Wed, 15 Mar 2023 14:45:31 GMT
            Connection:
              schema:
                type: string
              example:
                value: keep-alive
            Keep-Alive:
              schema:
                type: string
              example:
                value: timeout=5
          content:
            application/json:
              schema:
                type: object
                $ref: "#/components/schemas/rest_serviceResponse195"
              example: "[\n    {\n        \"ProductionType\": \"Other\",\n        \"ProductionTypeAbbrev\": \"other\",\n        \"ProductionTypeNote\": \"\"\n    },\n    {\n        \"ProductionType\": \"Wind Onshore\",\n        \"ProductionTypeAbbrev\": \"wind_onshore\",\n        \"ProductionTypeNote\": \"For DAPEEP refers to MV production only ENTSOe aggregates all\"\n    },\n    {\n        \"ProductionType\": \"Nuclear\",\n        \"ProductionTypeAbbrev\": \"nuclear\",\n        \"ProductionTypeNote\": \"\"\n    },\n    {\n        \"ProductionType\": \"Geothermal\",\n        \"ProductionTypeAbbrev\": \"geothermal\",\n        \"ProductionTypeNote\": \"\"\n    },\n    {\n        \"ProductionType\": \"Fossil Gas\",\n        \"ProductionTypeAbbrev\": \"fossil_gas\",\n        \"ProductionTypeNote\": \"\"\n    },\n    {\n        \"ProductionType\": \"Wind Offshore\",\n        \"ProductionTypeAbbrev\": \"wind_offshore\",\n        \"ProductionTypeNote\": \"\"\n    },\n    {\n        \"ProductionType\": \"Solar\",\n        \"ProductionTypeAbbrev\": \"solar\",\n        \"ProductionTypeNote\": \"For DAPEEP refers to MV production only ENTSOe aggregates all\"\n    },\n    {\n        \"ProductionType\": \"Fossil Hard coal\",\n        \"ProductionTypeAbbrev\": \"fossil_hard_coal\",\n        \"ProductionTypeNote\": \"\"\n    },\n    {\n        \"ProductionType\": \"Other renewable\",\n        \"ProductionTypeAbbrev\": \"other_renewable\",\n        \"ProductionTypeNote\": \"\"\n    },\n    {\n        \"ProductionType\": \"Biomass\",\n        \"ProductionTypeAbbrev\": \"biomass\",\n        \"ProductionTypeNote\": \"For DAPEEP refers to MV production only ENTSOe aggregates all\"\n    },\n    {\n        \"ProductionType\": \"Hydro Run-of-river and poundage\",\n        \"ProductionTypeAbbrev\": \"hydro_run_of_river_and_poundage\",\n        \"ProductionTypeNote\": \"\"\n    },\n    {\n        \"ProductionType\": \"Fossil Brown coal/Lignite\",\n        \"ProductionTypeAbbrev\": \"fossil_brown_coal_lignite\",\n        \"ProductionTypeNote\": \"\"\n    },\n    {\n        \"ProductionType\": \"Hydro Water Reservoir\",\n        \"ProductionTypeAbbrev\": \"hydro_water_reservoir\",\n        \"ProductionTypeNote\": \"\"\n    },\n    {\n        \"ProductionType\": \"Fossil Oil\",\n        \"ProductionTypeAbbrev\": \"fossil_oil\",\n        \"ProductionTypeNote\": \"\"\n    },\n    {\n        \"ProductionType\": \"Waste\",\n        \"ProductionTypeAbbrev\": \"waste\",\n        \"ProductionTypeNote\": \"\"\n    },\n    {\n        \"ProductionType\": \"Hydro Pumped Storage\",\n        \"ProductionTypeAbbrev\": \"hydro_pumped_storage\",\n        \"ProductionTypeNote\": \"\"\n    },\n    {\n        \"ProductionType\": \"Fossil Oil shale\",\n        \"ProductionTypeAbbrev\": \"fossil_oil_shale\",\n        \"ProductionTypeNote\": \"\"\n    },\n    {\n        \"ProductionType\": \"Fossil Peat\",\n        \"ProductionTypeAbbrev\": \"fossil_peat\",\n        \"ProductionTypeNote\": \"\"\n    },\n    {\n        \"ProductionType\": \"Fossil Coal-derived gas\",\n        \"ProductionTypeAbbrev\": \"fossil_coal_derived_gas\",\n        \"ProductionTypeNote\": \"\"\n    },\n    {\n        \"ProductionType\": \"Marine\",\n        \"ProductionTypeAbbrev\": \"marine\",\n        \"ProductionTypeNote\": \"\"\n    },\n    {\n        \"ProductionType\": \"AC Link\",\n        \"ProductionTypeAbbrev\": \"ac_link\",\n        \"ProductionTypeNote\": \"\"\n    },\n    {\n        \"ProductionType\": \"Substation\",\n        \"ProductionTypeAbbrev\": \"substation\",\n        \"ProductionTypeNote\": \"\"\n    },\n    {\n        \"ProductionType\": \"Transformer\",\n        \"ProductionTypeAbbrev\": \"transformer\",\n        \"ProductionTypeNote\": \"\"\n    },\n    {\n        \"ProductionType\": \"DC Link\",\n        \"ProductionTypeAbbrev\": \"dc_link\",\n        \"ProductionTypeNote\": \"\"\n    },\n    {\n        \"ProductionType\": \"\",\n        \"ProductionTypeAbbrev\": \"\",\n        \"ProductionTypeNote\": \"\"\n    },\n    {\n        \"ProductionType\": \"Solar Rooftop (DAPEEP only)\",\n        \"ProductionTypeAbbrev\": \"solar_rooftop_dapeep_only_\",\n        \"ProductionTypeNote\": \"DAPEEP only (MV)\"\n    },\n    {\n        \"ProductionType\": \"Mixed (DAPEEP only)\",\n        \"ProductionTypeAbbrev\": \"mixed_dapeep_only_\",\n        \"ProductionTypeNote\": \"DAPEEP only (MV)\"\n    },\n    {\n        \"ProductionType\": \"Mixed Dispatchable (DAPEEP only)\",\n        \"ProductionTypeAbbrev\": \"mixed_dispatchable_dapeep_only_\",\n        \"ProductionTypeNote\": \"DAPEEP only (MV)\"\n    },\n    {\n        \"ProductionType\": \"Small Hydro\",\n        \"ProductionTypeAbbrev\": \"small_hydro\",\n        \"ProductionTypeNote\": \"DAPEEP reports hydro production connected to MV only\"\n    }\n]"
                $schema: http://json-schema.org/draft-04/schema#
                type: array
                items:
                  type: object
                  properties:
                    ProductionType:
                      type: string
                    ProductionTypeAbbrev:
                      type: string
                    ProductionTypeNote:
                      type: string
                  required:
                    - ProductionType
                    - ProductionTypeAbbrev
                    - ProductionTypeNote
components:
  schemas:
     rest_service13request:
       type: object
       properties: 
         areaRef: 
           type:  string
         timezone: 
           type:  string
         prodType: 
           type:  string
     rest_service38request:
       type: object
       properties: 
         areaRef: 
           type:  string
         prodType: 
           type:  string
     rest_service62request:
       type: object
       properties: 
         areaRef: 
           type:  string
         prodType: 
           type:  string
     rest_service86request:
       type: object
       properties: 
         areaRef: 
           type:  string
     rest_service109request:
       type: object
       properties: 
         areaRef: 
           type:  string
     rest_serviceResponse195:
       type: object
       properties: 
         example: 
           $ref: "#/components/schemas/rest_serviceResponse195_example"
     rest_serviceResponse195_example:
       type: object
       properties: 
         items: 
           $ref: "#/components/schemas/rest_serviceResponse195_items"
     rest_serviceResponse195_items:
       type: object
       properties: 
         ProductionType: 
           type:  string
         ProductionTypeAbbrev: 
           type:  string
         ProductionTypeNote: 
           type:  string
