openapi: 3.0.3
info:
  title: My Api Refined
  version: 1.0.0
paths:
  /cities:
    post:
      description: Given a city and its corresponding ID return the country and its
        corresponding ID
      operationId: city_Explorer
      x-codegen-request-body-name: country_name
      requestBody:
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/Country_name'
            example: "{\r\n\"id_country\" : \"1\",\r\n\"country\" : \"Greece\" \r\n\
              }"
        required: true
      responses:
        200:
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/City_name'
              example: "{\r\n    \"req_body\": {\r\n        \"id_country\": \"1\"\
                ,\r\n        \"country\": \"Greece\"\r\n    },\r\n    \"cities\":\
                \ [\r\n        {\r\n            \"id_city\": \"1\",\r\n          \
                \  \"city\": \"Athens\"\r\n        },\r\n        {\r\n           \
                \ \"id_city\": \"2\",\r\n            \"city\": \"Piraeus\"\r\n   \
                \     }\r\n    ]\r\n}"
  /countries:
    post:
      description: Get a list of countries with their corresponding IDs
      operationId: country_Explorer
      responses:
        200:
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Country_name'
              example: "[\r\n    {\r\n        \"id_country\": \"1\",\r\n        \"\
                country\": \"Greece\"\r\n    },\r\n    {\r\n        \"id_country\"\
                : \"2\",\r\n        \"country\": \"France\"\r\n    },\r\n    {\r\n\
                \        \"id_country\": \"3\",\r\n        \"country\": \"Japan\"\r\
                \n    }\r\n]\r\n"
components:
  schemas:
    City_name:
      required:
      - req_body
      type: object
      properties:
        cities:
          $ref: '#/components/schemas/cities_class'
        req_body:
          $ref: '#/components/schemas/req_body_class'
    Country_name:
      type: object
      properties:
        id_country:
          type: string
        country:
          type: string
    req_body_class:
      type: object
      properties:
        id_city:
          type: string
        city:
          type: string
    cities_class:
      type: object
      properties:
        id_city:
          type: string
        city:
          type: string
